"""Initial Homeconomy module setup

Revision ID: 3f7de9690eef
Revises: 
Create Date: 2024-11-12 17:07:47.413489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7de9690eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coins')
        batch_op.drop_column('family_id')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
